### ISSUE TITLE
New CSS style for Polymer 2

### ISSUE THREAD

**Issue by fanthos** [bahrus/billboard-charts#1]
According the following links,
https://github.com/Polymer/polymer/pull/4344
and 
https://github.com/Polymer/polymer/blob/master/test/unit/styling-import.html
the CSS import block should write like this:
```html
<dom-module id="billboard-charts">
  <link rel="import" type="css" href="../billboard.js/dist/billboard.css">
  <template>
```

**Comment by bahrus** [comment]
Thanks for the feedback, @fanthos !  I think the Polymer team owes us a clear explanation on where we go from here as far as styling.  I'm a little perplexed, frankly.

[This link](https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom#external-stylesheets) seems to indicate that what you are suggesting is deprecated.

When I read [this article](https://www.smashingmagazine.com/2016/12/styling-web-components-using-a-shared-style-sheet/#link-relstylesheet-in-the-shadow-dom), my take away was to adopt the approach I followed.  It is correct that the Polymer documentation has yet to weigh in on this approach, positive or negative.  I've asked them, but haven't received any answers.  I'm thinking of also providing the option to use [style modules](https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom#style-modules), if that works better for some cases.

Let me know if you are encountering any issues as a result of my off-the-beaten-path choice.  I'm very interested to know of any gotchas.

**Comment by fanthos** [comment]
Polymer/polymer#3837 stats this feature will keep.
The original code won't load the css at currect path on my computer using bower.

**Comment by fanthos** [comment]
Style module is a good idea if it supports raw file include, not sure they have it or not.
